// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FexFile } from "./FexFile";

export interface Fex { files: Array<FexFile>, dir: string, }