// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from "./FileType";

export interface FexFile { name: string, date: string, time: string, len: bigint, file_type: FileType, }